//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Plantation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignedtask
    {
        public int ass_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> t_id { get; set; }
    
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}
