//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Plantation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assigned
    {
        public int assigned_id { get; set; }
        public Nullable<int> ass_id { get; set; }
        public Nullable<int> v_id { get; set; }
    
        public virtual assignment assignment { get; set; }
        public virtual volunteer volunteer { get; set; }
    }
}
