//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Plantation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authentication
    {
        public int au_id { get; set; }
        public Nullable<int> a_id { get; set; }
        public string a_email { get; set; }
        public string a_password { get; set; }
        public string a_type { get; set; }
        public string status { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
