//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Plantation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tree_plantation_dbEntities : DbContext
    {
        public tree_plantation_dbEntities()
            : base("name=tree_plantation_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<assigned> assigneds { get; set; }
        public virtual DbSet<assignedtask> assignedtasks { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<authentication> authentications { get; set; }
        public virtual DbSet<donation> donations { get; set; }
        public virtual DbSet<donor> donors { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<volunteer> volunteers { get; set; }
    }
}
