//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tree_Plantation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int r_id { get; set; }
        public Nullable<int> v_id { get; set; }
        public Nullable<int> amount { get; set; }
        public string time { get; set; }
        public string status { get; set; }
    
        public virtual volunteer volunteer { get; set; }
    }
}
